name: 'Deploy'

on:
  push:
    branches:
      - feature/ci
      - develop

jobs:
  build:
    name: Build project

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Clean install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy Infra
        if: ${{ contains(github.event.head_commit.message, 'chore(infra):') }}
        run: terraform apply -auto-approve # TODO: build backend config and pass it in arguments

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Sync files to S3
        run: 'aws s3 sync build s3://${{ vars.DEV_BUCKET_NAME }} --delete'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
